### ISSUE TITLE
[S1-UIUX] USER : Welcome & Home Page

### ISSUE THREAD

**Issue by araveta** [SI-RPL-2022/SI43INT_A_ELAUNDRY#4]
UI/UX merealisasikan tampilan dari welcome & home page.

**Comment by bungahu09** [comment]
https://drive.google.com/file/d/1vWlpvh6eKyz9Ty7DJDXoBfK0H161yfiE/view?usp=sharing
![Untitled_design-removebg-preview](https://user-images.githubusercontent.com/92161017/163787983-27d33138-7d0e-4db8-9b7c-661201942255.png)

**Comment by bungahu09** [comment]
https://drive.google.com/file/d/1vWlpvh6eKyz9Ty7DJDXoBfK0H161yfiE/view?usp=sharing
![Untitled_design-removebg-preview](https://user-images.githubusercontent.com/92161017/163788755-e5d246a8-9315-4785-a1ac-c50faf5b19de.png)

**Comment by bungahu09** [comment]
logo web:
https://drive.google.com/file/d/1Z5Yevj9-hzrvyxT7DK7f0d7wcpLgfCvJ/view?usp=sharing
![WhatsApp_Image_2022-04-18_at_3 51 28_PM-removebg-preview](https://user-images.githubusercontent.com/92161017/163793748-31c880b9-ac0e-48dc-a704-40412204bdc1.png)

**Comment by grepanditha17** [comment]
![image](https://user-images.githubusercontent.com/92254013/163819914-b1192b3d-773b-479f-bc10-517299ef0791.png)

UI/UX WELCOME PAGE
